# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - 8000:80
            # - '${APP_PORT:-8000}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

            #    Add a local database dump to be imported on startup
            - './db:/docker-entrypoint-initdb.d'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    # Add a database management tool like phpMyAdmin

    phpmyadmin:
        depends_on:
            - mysql
        image: 'phpmyadmin/phpmyadmin:latest'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        networks:
            - sail
        ports:
            - 8080:80
        # - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'

        # Add a front-end server like Apache
        # apache:
        #     depends_on:
        #         - laravel.test
        #     image: 'httpd:latest'
        #     volumes:
        #         - '.:/var/www/html'
        #     networks:
        #         - sail
        #     ports:
        #         - 8001:80

        # Add a load balancer like Nginx

    # Add a local Node database data generater project
    node:
        depends_on:
            - laravel.test
            - mysql
        build:
            context: ./data-generator
            # dockerfile: Dockerfile

            #command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
        networks:
            - sail
        # volumes:
        #     - ./data-generator:/generator
    # api1:
    #     build: .
    #     volumes:
    #         - .:/src/api
    #     depends_on:
    #         - mysql
    #     networks:
    #         - sail

    # api2:
    #     build: .
    #     volumes:
    #         - .:/src/api
    #     depends_on:
    #         - mysql
    #     networks:
    #         - sail

    frontend:
        build: ./Front-end
        volumes:
            - ./Front-end:/var/www/html
        networks:
            - sail

    proxy:
        image: 'nginx:latest'
        volumes:
            # - '.:/var/www/html'
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - sail
        ports:
            - 80:80
        depends_on:
            - laravel.test
            # - api1
            # - api2
            - frontend
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
